# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='thumbnail',
            field=models.CharField(default='https://i.imgur.com/NqomU87s.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='caption',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
