# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0002_auto_20170528_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobject',
            name='id_nb',
            field=models.IntegerField(default=0),
        ),
    ]
