# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0004_subreddit_time_ago_of_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageobject',
            name='id_nb',
        ),
        migrations.AddField(
            model_name='imageobject',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
