# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0006_auto_20170528_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobject',
            name='sub_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
